
schema_version = "1.0.0"
id = "maya_viewport_operation"
version = "1.0.0"
name = "Maya Viewport Operation"
tagline = "This addon simulates the viewport operations (1, 2, 3, 4, 5, 6, 7) in maya to blender"
maintainer = "TinkerBoi <support@tinkerboi.com>"
type = "add-on"
website = "https://github.com/BlenderBoi/maya_viewport_operation"
tags = ["Utility"]
blender_version_min = "4.2.0"

license = [
  "SPDX:GPL-2.0-or-later",
]

